package mybatis.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.ID
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    private String courseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.CREDITS
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    private Double credits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.HOURS
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    private Integer hours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    private Long universityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.ID
     *
     * @return the value of PUBLIC.COURSE.ID
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.ID
     *
     * @param id the value for PUBLIC.COURSE.ID
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @return the value of PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @param courseName the value for PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.CREDITS
     *
     * @return the value of PUBLIC.COURSE.CREDITS
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public Double getCredits() {
        return credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.CREDITS
     *
     * @param credits the value for PUBLIC.COURSE.CREDITS
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public void setCredits(Double credits) {
        this.credits = credits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.HOURS
     *
     * @return the value of PUBLIC.COURSE.HOURS
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public Integer getHours() {
        return hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.HOURS
     *
     * @param hours the value for PUBLIC.COURSE.HOURS
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public void setHours(Integer hours) {
        this.hours = hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @return the value of PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @param universityId the value for PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }
}